spring:
  # 임시 계정 / 임시 비밀번호
  security:
    user:
      name: user
      password: 1234
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_board
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
  session:
    storage-type: redis
  redis:
    host: localhost
    port: 6379
logging:
  # 로그파일 경로와 파일명 지정
  file:
    # 자동으로 폴더 및 로그 파일 생성 (하드 디스크에 저장)
    name: logs/app.log
  level:
    # trace < debug < info < error 순서의 로그 레벨을 가짐
    # info로 설정 시 trace, debug 로그는 출력되지 않음
    root: info